---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: HarvestTrading
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: HarvestTrading
    apps.tanzu.vmware.com/has-tests: "false"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: HarvestTrading
    tanzu.app.live.view.application.actuator.port: "9090"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
    - name: BP_DOTNET_PROJECT_PATH
      value: "src/HarvestTradingApi"
    - name: BP_DOTNET_PUBLISH_FLAGS
      value: "--self-contained=true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/franktylerva/HarvestTradingCompany.git
      ref:
        branch: main
        
  serviceClaims:
    - name: products-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: products-db